version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: sleep infinity
    network_mode: service:libretranslate

  libretranslate:
    image: libretranslate/libretranslate:latest
    restart: unless-stopped
    ports:
      "5000:5000"
    environment:
      - LT_UPDATE_MODELS=true
    volumes:
      - libretranslate_models:/home/libretranslate/.local:rw

volumes:
  libretranslate_models: