version: '3.8'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    command: sleep infinity
    # Runs app on the same network as the database container, allows "forwardPorts" in devcontainer.json function.
    network_mode: service:libretranslate

  libretranslate:
    image: libretranslate/libretranslate:latest
    restart: unless-stopped
    ports:
      - "5001:5000"
