services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    command: sleep infinity
    network_mode: service:libretranslate
    links:
      - libretranslate

  libretranslate:
    container_name: LibreTranslate
    image: libretranslate/libretranslate:latest
    restart: unless-stopped
    ports:
      - "8000:5000"
    healthcheck:
      test: ['CMD-SHELL', './venv/bin/python scripts/healthcheck.py']
    security_opt:
      - no-new-privileges:true
    environment:
      - LT_DEBUG=true
      - LT_LOAD_ONLY=en,es
      - LT_UPDATE_MODELS=true
      - LT_FRONTEND_LANGUAGE_SOURCE="en"
      - LT_FRONTEND_LANGUAGE_TARGET="es"
    volumes:
      - libretranslate_api_keys:/app/db
      - libretranslate_local:/home/libretranslate/.local

volumes:
  libretranslate_api_keys:
  libretranslate_local:
  
  
