services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    command: sleep infinity
    network_mode: service:libretranslate

  libretranslate:
    container_name: LibreTranslate
    image: libretranslate/libretranslate:latest
    ports:
      - "5001:5000"
    healthcheck:
      test: ['CMD-SHELL', './venv/bin/python scripts/healthcheck.py']
    security_opt:
      - no-new-privileges:true
    environment:
      - LT_LOAD_ONLY=en,es
      - LT_UPDATE_MODELS=true
      - LT_SUGGESTIONS=false
      - LT_METRICS=true
      - LT_API_KEYS=false
      - LT_API_KEYS_DB_PATH=/app/db/api_keys.db
    volumes:
      - libretranslate_api_keys:/app/db
      - libretranslate_local:/home/libretranslate/.local

volumes:
  libretranslate_api_keys:
  libretranslate_local:
  
  
